Better detection of Python prerequisites in configure
Don't try to build the Python extension if swig or doxygen are missing,
and warn the user.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -728,6 +728,8 @@ DYLIB_VAR
 GYOTO_PLUGIN_SFX
 LDFLAGS_EXEC
 CXXFLAGS_EXEC
+SWIG_LIB
+SWIG
 KPSEWHICH
 BIBTEX
 PDFLATEX
@@ -749,8 +751,6 @@ BOOST_CPPFLAGS
 DISTCHECK_CONFIGURE_FLAGS
 BOOST_ROOT
 HAVE_CXX11
-SWIG_LIB
-SWIG
 VIRTUALENV_FLAGS
 VIRTUALENV
 PYTHON_EXTENSION_SUFFIX
@@ -18309,131 +18309,6 @@ else $as_nop
 fi
 
 
-
-        # Ubuntu has swig 2.0 as /usr/bin/swig2.0
-        # Debian has swig 3.0 as /usr/bin/swig3.0
-        for ac_prog in swig swig4.0 swig3.0 swig2.0
-do
-  # Extract the first word of "$ac_prog", so it can be a program name with args.
-set dummy $ac_prog; ac_word=$2
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
-printf %s "checking for $ac_word... " >&6; }
-if test ${ac_cv_path_SWIG+y}
-then :
-  printf %s "(cached) " >&6
-else $as_nop
-  case $SWIG in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_SWIG="$SWIG" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  case $as_dir in #(((
-    '') as_dir=./ ;;
-    */) ;;
-    *) as_dir=$as_dir/ ;;
-  esac
-    for ac_exec_ext in '' $ac_executable_extensions; do
-  if as_fn_executable_p "$as_dir$ac_word$ac_exec_ext"; then
-    ac_cv_path_SWIG="$as_dir$ac_word$ac_exec_ext"
-    printf "%s\n" "$as_me:${as_lineno-$LINENO}: found $as_dir$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-  done
-IFS=$as_save_IFS
-
-  ;;
-esac
-fi
-SWIG=$ac_cv_path_SWIG
-if test -n "$SWIG"; then
-  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $SWIG" >&5
-printf "%s\n" "$SWIG" >&6; }
-else
-  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
-printf "%s\n" "no" >&6; }
-fi
-
-
-  test -n "$SWIG" && break
-done
-
-        if test -z "$SWIG" ; then
-                :
-        elif test -n "2.0" ; then
-                { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking SWIG version" >&5
-printf %s "checking SWIG version... " >&6; }
-                swig_version=`$SWIG -version 2>&1 | grep 'SWIG Version' | sed 's/.*\([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\).*/\1/g'`
-                { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $swig_version" >&5
-printf "%s\n" "$swig_version" >&6; }
-                if test -n "$swig_version" ; then
-                        # Calculate the required version number components
-                        required=2.0
-                        required_major=`echo $required | sed 's/[^0-9].*//'`
-                        if test -z "$required_major" ; then
-                                required_major=0
-                        fi
-                        required=`echo $required | sed 's/[0-9]*[^0-9]//'`
-                        required_minor=`echo $required | sed 's/[^0-9].*//'`
-                        if test -z "$required_minor" ; then
-                                required_minor=0
-                        fi
-                        required=`echo $required | sed 's/[0-9]*[^0-9]//'`
-                        required_patch=`echo $required | sed 's/[^0-9].*//'`
-                        if test -z "$required_patch" ; then
-                                required_patch=0
-                        fi
-                        # Calculate the available version number components
-                        available=$swig_version
-                        available_major=`echo $available | sed 's/[^0-9].*//'`
-                        if test -z "$available_major" ; then
-                                available_major=0
-                        fi
-                        available=`echo $available | sed 's/[0-9]*[^0-9]//'`
-                        available_minor=`echo $available | sed 's/[^0-9].*//'`
-                        if test -z "$available_minor" ; then
-                                available_minor=0
-                        fi
-                        available=`echo $available | sed 's/[0-9]*[^0-9]//'`
-                        available_patch=`echo $available | sed 's/[^0-9].*//'`
-                        if test -z "$available_patch" ; then
-                                available_patch=0
-                        fi
-                        # Convert the version tuple into a single number for easier comparison.
-                        # Using base 100 should be safe since SWIG internally uses BCD values
-                        # to encode its version number.
-                        required_swig_vernum=`expr $required_major \* 10000 \
-                            \+ $required_minor \* 100 \+ $required_patch`
-                        available_swig_vernum=`expr $available_major \* 10000 \
-                            \+ $available_minor \* 100 \+ $available_patch`
-
-                        if test $available_swig_vernum -lt $required_swig_vernum; then
-                                { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: SWIG version >= 2.0 is required.  You have $swig_version." >&5
-printf "%s\n" "$as_me: WARNING: SWIG version >= 2.0 is required.  You have $swig_version." >&2;}
-                                SWIG=''
-
-                        else
-                                { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for SWIG library" >&5
-printf %s "checking for SWIG library... " >&6; }
-                                SWIG_LIB=`$SWIG -swiglib`
-                                { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $SWIG_LIB" >&5
-printf "%s\n" "$SWIG_LIB" >&6; }
-
-                        fi
-                else
-                        { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: cannot determine SWIG version" >&5
-printf "%s\n" "$as_me: WARNING: cannot determine SWIG version" >&2;}
-                        SWIG=''
-
-                fi
-        fi
-
-
-
 # DONE WITH PYTHON STUFF
 
 # Checks for programs.
@@ -20235,6 +20110,130 @@ fi
 
   test -n "$KPSEWHICH" && break
 done
+
+
+        # Ubuntu has swig 2.0 as /usr/bin/swig2.0
+        # Debian has swig 3.0 as /usr/bin/swig3.0
+        for ac_prog in swig swig4.0 swig3.0 swig2.0
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+printf %s "checking for $ac_word... " >&6; }
+if test ${ac_cv_path_SWIG+y}
+then :
+  printf %s "(cached) " >&6
+else $as_nop
+  case $SWIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_SWIG="$SWIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  case $as_dir in #(((
+    '') as_dir=./ ;;
+    */) ;;
+    *) as_dir=$as_dir/ ;;
+  esac
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if as_fn_executable_p "$as_dir$ac_word$ac_exec_ext"; then
+    ac_cv_path_SWIG="$as_dir$ac_word$ac_exec_ext"
+    printf "%s\n" "$as_me:${as_lineno-$LINENO}: found $as_dir$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+SWIG=$ac_cv_path_SWIG
+if test -n "$SWIG"; then
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $SWIG" >&5
+printf "%s\n" "$SWIG" >&6; }
+else
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+printf "%s\n" "no" >&6; }
+fi
+
+
+  test -n "$SWIG" && break
+done
+
+        if test -z "$SWIG" ; then
+                :
+        elif test -n "2.0" ; then
+                { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking SWIG version" >&5
+printf %s "checking SWIG version... " >&6; }
+                swig_version=`$SWIG -version 2>&1 | grep 'SWIG Version' | sed 's/.*\([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\).*/\1/g'`
+                { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $swig_version" >&5
+printf "%s\n" "$swig_version" >&6; }
+                if test -n "$swig_version" ; then
+                        # Calculate the required version number components
+                        required=2.0
+                        required_major=`echo $required | sed 's/[^0-9].*//'`
+                        if test -z "$required_major" ; then
+                                required_major=0
+                        fi
+                        required=`echo $required | sed 's/[0-9]*[^0-9]//'`
+                        required_minor=`echo $required | sed 's/[^0-9].*//'`
+                        if test -z "$required_minor" ; then
+                                required_minor=0
+                        fi
+                        required=`echo $required | sed 's/[0-9]*[^0-9]//'`
+                        required_patch=`echo $required | sed 's/[^0-9].*//'`
+                        if test -z "$required_patch" ; then
+                                required_patch=0
+                        fi
+                        # Calculate the available version number components
+                        available=$swig_version
+                        available_major=`echo $available | sed 's/[^0-9].*//'`
+                        if test -z "$available_major" ; then
+                                available_major=0
+                        fi
+                        available=`echo $available | sed 's/[0-9]*[^0-9]//'`
+                        available_minor=`echo $available | sed 's/[^0-9].*//'`
+                        if test -z "$available_minor" ; then
+                                available_minor=0
+                        fi
+                        available=`echo $available | sed 's/[0-9]*[^0-9]//'`
+                        available_patch=`echo $available | sed 's/[^0-9].*//'`
+                        if test -z "$available_patch" ; then
+                                available_patch=0
+                        fi
+                        # Convert the version tuple into a single number for easier comparison.
+                        # Using base 100 should be safe since SWIG internally uses BCD values
+                        # to encode its version number.
+                        required_swig_vernum=`expr $required_major \* 10000 \
+                            \+ $required_minor \* 100 \+ $required_patch`
+                        available_swig_vernum=`expr $available_major \* 10000 \
+                            \+ $available_minor \* 100 \+ $available_patch`
+
+                        if test $available_swig_vernum -lt $required_swig_vernum; then
+                                { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: SWIG version >= 2.0 is required.  You have $swig_version." >&5
+printf "%s\n" "$as_me: WARNING: SWIG version >= 2.0 is required.  You have $swig_version." >&2;}
+                                SWIG=''
+
+                        else
+                                { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for SWIG library" >&5
+printf %s "checking for SWIG library... " >&6; }
+                                SWIG_LIB=`$SWIG -swiglib`
+                                { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $SWIG_LIB" >&5
+printf "%s\n" "$SWIG_LIB" >&6; }
+
+                        fi
+                else
+                        { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: cannot determine SWIG version" >&5
+printf "%s\n" "$as_me: WARNING: cannot determine SWIG version" >&2;}
+                        SWIG=''
+
+                fi
+        fi
+
 
 
 # Provide additional defaults for user variables
@@ -24026,7 +24025,24 @@ then :
 
 
 fi
-if test "x$PYTHON" != "x"
+missing_for_python=""
+if test "x$PYTHON" = x
+then :
+  missing_for_python="$missing_for_python PYTHON"
+fi
+if test "x$PYTHON_CONFIG" = x
+then :
+  missing_for_python="$missing_for_python PYTHON-CONFIG"
+fi
+if test "x$DOXYGEN" = x
+then :
+  missing_for_python="$missing_for_python DOXYGEN"
+fi
+if test "x$SWIG" = x
+then :
+  missing_for_python="$missing_for_python SWIG"
+fi
+if test "x$missing_for_python" = "x"
 then :
 
    ac_config_files="$ac_config_files python/Makefile python/setup.py"
@@ -26833,6 +26849,28 @@ fi
 
 ########################## SUMMARY ############################
 
+if test "x$missing_for_python" != "x"
+then :
+
+   { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING:
+
+                   Building without$missing_for_python.
+
+                *** The Python extension will not be built! ***
+
+      Gyoto can still be used as a C++ library and through the gyoto executable.
+     " >&5
+printf "%s\n" "$as_me: WARNING:
+
+                   Building without$missing_for_python.
+
+                *** The Python extension will not be built! ***
+
+      Gyoto can still be used as a C++ library and through the gyoto executable.
+     " >&2;}
+
+fi
+
 if test "x$have_xerces" == "xno" || test "x$have_cfitsio" == "xno"
 then :
 
@@ -26842,7 +26880,7 @@ then :
 
                 *** The gyoto executable will not be built! ***
 
-      Gyoto can still be used as a C++ library and through the Yorick plug-in
+      Gyoto can still be used as a C++ library and through the Python extension
         (although without XML support and/or without certain object types).
      " >&5
 printf "%s\n" "$as_me: WARNING:
@@ -26851,11 +26889,12 @@ printf "%s\n" "$as_me: WARNING:
 
                 *** The gyoto executable will not be built! ***
 
-      Gyoto can still be used as a C++ library and through the Yorick plug-in
+      Gyoto can still be used as a C++ library and through the Python extension
         (although without XML support and/or without certain object types).
      " >&2;}
 
 fi
+
 if test "x$have_udunits" == "xno"
 then :
 
@@ -26875,6 +26914,7 @@ printf "%s\n" "$as_me: WARNING:
      " >&2;}
 
 fi
+
 if test "x$have_boost" == "xno"
 then :
 
@@ -26900,6 +26940,7 @@ printf "%s\n" "$as_me: WARNING:
      " >&2;}
 
 fi
+
 if test "x$have_2f1" == "xno"
 then :
 
@@ -26907,18 +26948,18 @@ then :
 
                          Building without 2F1
 
-                   *** Hypergeometric functions unavailable ***
+               *** Hypergeometric functions unavailable ***
 
-                      Astrobj::Jet requires ARBLIB or AEAE.
+               Astrobj::Jet requires FLINT, ARBLIB or AEAE.
 
      " >&5
 printf "%s\n" "$as_me: WARNING:
 
                          Building without 2F1
 
-                   *** Hypergeometric functions unavailable ***
+               *** Hypergeometric functions unavailable ***
 
-                      Astrobj::Jet requires ARBLIB or AEAE.
+               Astrobj::Jet requires FLINT, ARBLIB or AEAE.
 
      " >&2;}
 
